version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: ticketing-sales-postgres
    environment:
      POSTGRES_DB: ticketing_sales_db
      POSTGRES_USER: sales_user
      POSTGRES_PASSWORD: sales_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata_sales:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata_sales:
